### ISSUE TITLE
Failing to load move_vids

### ISSUE THREAD

**Issue by dennisgove** [ohrely/dancerator#1]
After creating a dance, the move videos fail to load on the screen. The stacktrace doesn't appear to contain any local calls so I'm wondering if it's a dependency thing.
 
```bash
[[u'neighbor balance', u'neighbor box the gnat', u'half hey'], [u'neghbor magnetize right melt', u'neighbor swing'], [u'left hand star 4 places', u'follows allemande left 1 1/2'], [u'partner balance', u'partner box the gnat', u'neighbor balance', u'petronella']]
127.0.0.1 - - [17/Feb/2017 18:12:24] "GET /dance/709 HTTP/1.1" 200 -
127.0.0.1 - - [17/Feb/2017 18:12:32] "GET /static/move_vids/allemande.mp4 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 56407)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```

I double checked the `requirements.txt` file and all looks good. Only other thing I can think of is this requires python 3.x.

```
:) 18:16:13-dennis@nemo ~/dev/dancerator $ pip install -r requirements.txt
Requirement already satisfied: blinker==1.4 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: decorator==4.0.4 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: Flask==0.10.1 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: Flask-DebugToolbar==0.10.0 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: Flask-SQLAlchemy==2.1 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: itsdangerous==0.24 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: Jinja2==2.8 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: MarkupSafe==0.23 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: networkx==1.10 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: python-dateutil==1.5 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied: requests==2.9.0 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 11))
Requirement already satisfied: SQLAlchemy==1.0.9 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 12))
Requirement already satisfied: virtualenv==13.1.2 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 13))
Requirement already satisfied: Werkzeug==0.10.4 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 14))
Requirement already satisfied: wheel==0.24.0 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 15))
```

**Comment by dennisgove** [comment]
It appears the videos have the proper permissions `-rwxr-xr-x` and they do play fine in Quicktime player.

**Comment by dennisgove** [comment]
Tried running with python 3.4 and then realized the code has python 2.x-isms, so it doesn't appear to be the wrong version of python. I think I've got some other dependency wrong.

Very cool dance creator - it's fun to see what comes out.

**Comment by dennisgove** [comment]
Looks like this is an issue in my browser - it's refusing to play .mp4s and closing the connection. Absolutely not related to any code in here. Sorry to creating the issue.
